
name: Deploy to Amazon ECS

on:
  push:
    branches: [ "dev" ]


permissions:
  contents: read

jobs:

  migrate:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: Run production migration
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy > at.json
      - name: get migration id
        run: jq 'Applying migration' at.json
      - name: Run rollback if deploy failed
        if: failure()
        env:
         DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate resolve --rolled-back

